@startuml Sequence diagram

activate Client 
Client -> ItemFactory : Request a random item 


activate ItemFactory

ItemFactory <-- ItemFactory : get decorations

activate ConcreteItem

ItemFactory -> ConcreteItem : create baseItem 
ItemFactory <-- ConcreteItem : returns item 

deactivate ConcreteItem

loop each decoration 
    ref over ItemFactory : apply decoration
end

ItemFactory --> Client : decorated item 
deactivate ItemFactory

deactivate Client 

@enduml
