@startuml Market

actor person

actor customer
actor salesman 

person <|-- customer
person <|-- salesman

rectangle {

    (buy item) 
    (haggle for item)
    (put item up for sale)
    (transfer money)
    (looking for items)
    (transfer money)

    note "if enough money" as buyNote
    note "not enough money" as haggleNote
    :customer: -- (looking for items) 
    :salesman: -- (put item up for sale)
    :salesman: -- (transfer money)

    (put item up for sale) .> (notify customers) : <<include>> 
    
    buyNote .. (buy item) : <<extend>>
    (looking for items) <. buyNote : <<extend>>

    haggleNote .. (haggle for item) 
    (looking for items) <.. haggleNote : <<extend>>

    (haggle for item) <.. (buy item) : <<extend>> 
    (haggle for item) <.. (purchase rejected) : <<extend>> 
    
    (purchase rejected) -- salesman
    note right of (purchase rejected) : Rejected by salesman
    (buy item) .> (transfer money) : <<include>>

}

@enduml
