@startuml Market

actor person

actor customer
actor salesman 

person <|-- customer
person <|-- salesman

rectangle "Market" {

    (buy item) 
    (bargain for item)
    (put item up for sale)
    (transfer money)
    (choose item)
    (consider bargain)
    (transfer money)

    note "if enough money" as buyNote
    note "almost enough money" as bargainNote
    :customer: -- (choose item) 
    :salesman: -- (put item up for sale)
    :salesman: -- (transfer money)
    
    buyNote .. (buy item)
    (choose item) <. buyNote : extends

    bargainNote .. (bargain for item) 
    (choose item) <.. bargainNote : extends

    (bargain for item) ..> (consider bargain)
    (consider bargain) ..> (buy item)
    (consider bargain) .. (put item up for sale)



    (buy item) .> (transfer money) : include 


    



}

@enduml
